### ISSUE TITLE
Change window.location

### ISSUE THREAD

**Issue by narasimha-1511** [narasimha-1511/react-contacts-app#1]
If you see the file https://github.com/narasimha-1511/react-contacts-app/blob/master/src/components/AddContact.js

in line no 18 : ` window.location ="/" `

i dont have mush experience wit this but their ` this.props.history.push("/") ` is not working and giving an error

**Comment by Thilagavathi1** [comment]
@narasimha-1511 i would like to work on this issue, could u please assign it to me?

**Comment by narasimha-1511** [comment]
go on @Thilagavathi1 :confetti_ball:

**Comment by Thilagavathi1** [comment]
@narasimha-1511 please review the [PR](https://github.com/narasimha-1511/react-contacts-app/pull/2) and let me know the feedbacks

**Comment by narasimha-1511** [comment]
Thank You @Thilagavathi1
